services:
  - type: web
    name: github-webhook-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask run --host=0.0.0.0 --port=10000
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGO_URL
        value: your-mongodb-atlas-uri-here
